function removeAccents(input) {
  return input.normalize("NFD").replace(/[\u0300-\u036f]/g, "");
}

document.addEventListener("DOMContentLoaded", function () {
  const searchInput = document.getElementById("search");
  const suggestionBox = document.getElementById("suggestions");

  const suggestions = [
    "Abonnements à des services de streaming",
    "Abreuvoir automatique pour chiens",
    "Abreuvoir automatique pour lapins",
    "Abreuvoir pour oiseaux",
    "Abyssin",
    "Accessoires",
    "Accessoires de coiffure",
    "Accessoires de décoration pour voiture",
    "Accessoires de manucure et de pédicure",
    "Accessoires de mode",
    "Accessoires de musculation",
    "Accessoires de natation",
    "Accessoires de nettoyage pour voiture",
    "Accessoires de plage et de mode guadeloupéens",
    "Accessoires de rangement pour voiture",
    "Accessoires de réalité virtuelle",
    "Accessoires pour cheveux",
    "Accessoires pour vidéoconférence",
    "Accordéons",
    "Accordéons piano",
    "Action Replay",
    "Adaptateur HDMI vers VGA",
    "Adaptateur de manette",
    "Adaptateur secteur avec ports USB",
    "Adaptateurs Bluetooth pour voiture",
    "Adaptateurs Lightning",
    "Adaptateurs Mini DisplayPort vers HDMI",
    "Adaptateurs Powerline",
    "Adaptateurs USB-C",
    "Adaptateurs Wi-Fi USB",
    "Adaptateurs de charge pour voiture",
    "Adaptateurs secteur universels",
    "Adhésifs conducteurs",
    "Adhésifs de réparation pour rétroviseurs",
    "Affiches de films",
    "Affiches déroulantes de films",
    "Afghanistan",
    "Afrique du Sud",
    "Agenda",
    "Agenda électronique",
    "Agendas",
    "Agendas avec motifs personnalisés",
    "Agendas électroniques synchronisables",
    "Agrafes",
    "Agrafeuse",
    "Agrafeuse sans agrafes",
    "Aimant télescopique",
    "Albanie",
    "Algérie",
    "Alimentation de laboratoire",
    "Alimentations à découpage",
    "Allemagne",
    "Amazon Luna",
    "Amiga",
    "Amiibo",
    "Amplificateurs audio",
    "Amplificateurs de casque",
    "Amplificateurs de casque audiophiles",
    "Amplificateurs de casque avec égalisation",
    "Amplificateurs de casque pour audiophiles",
    "Amplificateurs de précision",
    "Amplificateurs de puissance",
    "Amplificateurs de puissance haute performance",
    "Amplificateurs différentiels",
    "Amplificateurs home cinéma",
    "Amplificateurs home cinéma 7.1",
    "Amplificateurs opérationnels",
    "Amplificateurs pour casque avec DAC intégré",
    "Amplificateurs pour casque avec tubes à vide",
    "Amplificateurs pour casque de monitoring",
    "Amplificateurs stéréo",
    "Ampoules LED pour voiture",
    "Ampoules intelligentes",
    "Analog Stick",
    "Andorre",
    "Angklungs",
    "Angola",
    "Angora Turc",
    "Animal Crossing: New Horizons",
    "Anneau de dentition",
    "Antennes",
    "Anti-cernes",
    "Antigel",
    "Antigua-et-Barbuda",
    "Appareil de bricolage polyvalent",
    "Appareil de bureau intelligent",
    "Appareil de chauffage économique",
    "Appareil de climatisation portable",
    "Appareil de coiffure automatisée",
    "Appareil de communication holographique",
    "Appareil de communication sans fil",
    "Appareil de couture moderne",
    "Appareil de cuisine automatisée",
    "Appareil de diagnostic OBD",
    "Appareil de diagnostic automobile",
    "Appareil de divertissement interactif",
    "Appareil de fitness intelligent",
    "Appareil de jardinage automatisé",
    "Appareil de jeu en réalité virtuelle",
    "Appareil de maquillage numérique",
    "Appareil de massage",
    "Appareil de mesure automatisée",
    "Appareil de musculation",
    "Appareil de musculation connectée",
    "Appareil de navigation GPS",
    "Appareil de numérisation avancée",
    "Appareil de projection haute résolution",
    "Appareil de redressage carrosserie",
    "Appareil de relaxation virtuelle",
    "Appareil de santé personnalisée",
    "Appareil de soins de la peau",
    "Appareil de sonorisation sans fil",
    "Appareil de soudage MIG",
    "Appareil de stockage en ligne",
    "Appareil de surveillance à distance",
    "Appareil de sécurité domestique",
    "Appareil de traduction instantanée",
    "Appareil de traitement de données",
    "Appareil de traitement de l'image",
    "Appareil de transport électrique",
    "Appareil photo",
    "Appareil photo argentique",
    "Appareil photo bridge",
    "Appareil photo compact",
    "Appareil photo instantané",
    "Appareil photo jetable",
    "Appareil photo moyen format",
    "Appareil photo numérique",
    "Appareil photo panoramique",
    "Appareil photo reflex",
    "Appareil photo sous-marin",
    "Appareil à gaufres",
    "Appareil à raclette",
    "Appareils de cardio-training",
    "Appareils de fitness",
    "Appareils de projection portables",
    "Appareils domotiques",
    "Aquarium pour poissons",
    "Arabie saoudite",
    "Arbre à chat",
    "Arche de jeu pour oiseaux",
    "Argentine",
    "Arménie",
    "Arrache-rotule",
    "Arrache-rotule à crémaillère",
    "Arrosoir",
    "Articles de cuisine",
    "Articles de décoration",
    "Articles de plein air",
    "Articles de sport",
    "Articles ménagers",
    "Artisanat traditionnel guadeloupéen",
    "Aspirateur",
    "Aspirateur robot",
    "Aspirateur à cendres",
    "Aspirateur à main",
    "Aspirateur à poussière pour ordinateur",
    "Aspirateurs pour voiture",
    "Assassin's Creed II",
    "Assassin's Creed III",
    "Assassin's Creed Valhalla",
    "Assassin's Creed: Brotherhood",
    "Atari 2600",
    "Atari 5200",
    "Atari 7800",
    "Atari Jaguar",
    "Atmosphere",
    "Attache-doudou",
    "Attache-lit mobile",
    "Attache-lit à barreaux",
    "Attache-sucette",
    "Attache-sucette personnalisée",
    "Attaches de remorque",
    "Augmented Reality Glasses",
    "Aurora",
    "Australie",
    "Autriche",
    "Azerbaïdjan",
    "Bac",
    "Bac à foin pour rongeurs",
    "Bac à foin suspendu pour rongeurs",
    "Bac à litière",
    "Bac à litière autonettoyant",
    "Bac à sable pour chat",
    "Bac à sable pour chinchilla",
    "Bac à sable pour furets",
    "Backup Loader",
    "Bagpipes",
    "Bague",
    "Bague en argent",
    "Bahamas",
    "Bahreïn",
    "Baignoire pliable",
    "Balafons",
    "Balai à franges",
    "Balalaïkas",
    "Balance Board",
    "Balance de cuisine",
    "Balance de cuisine connectée",
    "Balance de précision",
    "Balancelle design",
    "Balancelle électrique",
    "Balançoire pour oiseaux",
    "Balle interactive pour chat",
    "Balles de golf",
    "Ballon de basket",
    "Ballon de football",
    "Ballon de handball",
    "Ballon de rugby",
    "Ballon de volleyball",
    "Ballons de basketball",
    "Ballons de football",
    "Ballons de handball",
    "Ballons de rugby",
    "Ballons de volley",
    "Banc de jardin",
    "Banc de musculation",
    "Bandes originales de films",
    "Bangladesh",
    "Barbade",
    "Barbecue à charbon",
    "Barbecue à gaz",
    "Barbecue électrique",
    "Barre de traction",
    "Barres de son",
    "Barres de toit",
    "Barres de toit universelles",
    "Barrière de lit",
    "Barrière de sécurité",
    "Basses électriques",
    "Basset Hound",
    "Bassin de jardin",
    "Bateau gonflable",
    "Batman: Arkham Asylum",
    "Batman: Arkham City",
    "Batman: Arkham Knight",
    "Batterie externe haute capacité",
    "Batteries acoustiques",
    "Batteries de voiture",
    "Batteries externes",
    "Batteries externes solaires",
    "Batteur à main",
    "Batteurs électriques",
    "Battlefield 1",
    "Baumes à lèvres hydratants",
    "Baumes à lèvres teintés",
    "Bavoir en coton",
    "Bavoir imperméable",
    "Bavoir à manches",
    "Bavoir à manches longues",
    "Beagle",
    "Belgique",
    "Belize",
    "Bengal",
    "Berceau en bois",
    "Berceau en osier",
    "Berger Allemand",
    "Berger Australien",
    "Bhoutan",
    "Biberon en plastique",
    "Biberon en verre",
    "Biberon pour rongeurs",
    "Bichon Frisé",
    "Bichon Maltais",
    "Bijoux",
    "Bijoux inspirés de la Guadeloupe",
    "Billes de soudure",
    "BioShock",
    "BioShock Infinite",
    "Bioshock 2",
    "Birman",
    "Birmanie (Myanmar)",
    "Biélorussie",
    "Blender",
    "Blender haute performance",
    "Blenders",
    "Blocs à couteaux",
    "Bloodborne",
    "Blouson en cuir",
    "Blu-rays de films populaires",
    "Body en coton",
    "Bol",
    "Bol suspendu pour rongeurs",
    "Bolivie",
    "Bols mélangeurs",
    "Bongo Controller",
    "Bongos",
    "Bootloader",
    "Border Collie",
    "Borderlands",
    "Borderlands 2",
    "Borderlands 3",
    "Bosnie-Herzégovine",
    "Boston Terrier",
    "Botswana",
    "Boucles",
    "Boucles d'oreilles créoles",
    "Boucles d'oreilles en perles",
    "Boucleur automatique",
    "Boucleur à cheveux",
    "Boucleur à vapeur",
    "Bougie parfumée",
    "Bouilloire en acier inoxydable",
    "Bouilloire à café",
    "Bouilloire à sifflet",
    "Bouilloire à thé",
    "Bouilloire électrique",
    "Bouilloire électrique design",
    "Bouilloire électrique en acier inoxydable",
    "Bouilloire électrique en inox",
    "Bouilloire électrique en plastique",
    "Bouilloire électrique en verre",
    "Bouilloire électrique programmable",
    "Bouilloire électrique rétro",
    "Bouilloire électrique sans fil",
    "Bouilloires électriques",
    "Boule de pétanque",
    "Bouledogue américain",
    "Bouledogue anglais",
    "Bouledogue français",
    "Boules de pétanque",
    "Boussole",
    "Boussole électronique",
    "Bouteille d'eau réutilisable",
    "Bouteille de vin",
    "Bouteilles d'eau réutilisables avec infuseur",
    "Bouteilles de rhum agricole guadeloupéen",
    "Bouée de sauvetage",
    "Bouée gonflable",
    "Bouée géante",
    "Bouée licorne gonflable",
    "Boxer",
    "Boîte de crayons de couleur",
    "Boîte de mouchoirs en papier",
    "Boîte de rangement pour maquillage",
    "Boîte à bijoux",
    "Boîte à bijoux musicale",
    "Boîte à biscuits",
    "Boîte à chaussures",
    "Boîte à compartiments",
    "Boîte à céréales",
    "Boîte à lunch",
    "Boîte à musique",
    "Boîte à outils",
    "Boîte à pharmacie",
    "Boîte à épices",
    "Boîtes à lunch isothermes",
    "Boîtiers de jonction électrique",
    "Boîtiers de protection pour smartphones",
    "Boîtiers de protection pour tablettes",
    "Boîtiers pour modules électroniques",
    "Boîtiers pour ordinateurs",
    "Boîtiers pour projets électroniques",
    "Bracelet connecté",
    "Bracelets connectés",
    "Brick Protection",
    "Briquet",
    "Briquet tempête",
    "British Shorthair",
    "Brosse de nettoyage",
    "Brosse pour animal de compagnie",
    "Brosse pour bébé",
    "Brosse à WC",
    "Brosse à chaussures",
    "Brosse à cheveux",
    "Brosse à dents pour bébé",
    "Brosse à dents pour enfants",
    "Brosse à dents électrique",
    "Brosse à légumes",
    "Brosses antistatiques",
    "Brosses de maquillage",
    "Brucelles de précision",
    "Brunei",
    "Brésil",
    "Bulgarie",
    "Bulldog",
    "Bulldog français",
    "Burkina Faso",
    "Burundi",
    "Bâtons de ski",
    "Bénin",
    "CFW Installation Guide",
    "Cabo Verde",
    "Caches de plaque d'immatriculation",
    "Caches de roues de secours",
    "Cadenas",
    "Cadenas Bluetooth",
    "Cadenas à empreinte digitale",
    "Cadre photo en argent",
    "Cadre photo en bois",
    "Cadre photo magnétique",
    "Cadre photo numérique",
    "Cafetière à dosettes",
    "Cafetières",
    "Café et épices de Guadeloupe",
    "Cage de reptile",
    "Cage de transport pour animaux",
    "Cage pour chinchilla",
    "Cage pour hamster",
    "Cage pour lapin",
    "Cage pour oiseaux",
    "Cage pour rongeurs",
    "Cage à insectes",
    "Cahier de notes",
    "Cahiers",
    "Cahiers de brouillon",
    "Cahiers de composition",
    "Cahiers de composition à couverture personnalisée",
    "Cahiers de devoirs",
    "Cahiers de devoirs avec grille pour plannification",
    "Cahiers à lignes de différentes tailles",
    "Cahiers à spirale",
    "Cahiers à spirale à motifs",
    "Caisse à outils",
    "Caisse à outils roulante",
    "Cajons",
    "Calculatrice",
    "Calculatrice scientifique",
    "Calendrier mural",
    "Cales de calage",
    "Call of Duty: Black Ops",
    "Call of Duty: Black Ops II",
    "Call of Duty: Modern Warfare",
    "Call of Duty: Modern Warfare 2",
    "Cambodge",
    "Camera Attachment",
    "Cameroun",
    "Caméra",
    "Caméra d'action",
    "Caméra de diffusion",
    "Caméra de surveillance",
    "Caméra panoramique",
    "Caméras de recul",
    "Caméras de surveillance sans fil",
    "Caméras de sécurité",
    "Caméras de sécurité domestique",
    "Caméras embarquées",
    "Canada",
    "Canapé",
    "Canapé modulaire",
    "Canari",
    "Cane Corso",
    "Caniche",
    "Canne à pêche",
    "Cannes de marche nordique",
    "Cannes à pêche",
    "Cape de bain moelleuse",
    "Cape de bain à capuche",
    "Capteurs d'humidité",
    "Capteurs d'ouverture de porte",
    "Capteurs de lumière ambiante",
    "Capteurs de mouvement",
    "Capteurs de pression",
    "Capteurs de proximité",
    "Capteurs de température",
    "Capteurs électroniques",
    "Carafe filtrante",
    "Carlin",
    "Carnet",
    "Carnet de croquis",
    "Carte de capture",
    "Cartes SD",
    "Cartes de développement",
    "Cartes de formation en micro soudure",
    "Cartes géographiques",
    "Cartes géographiques murales",
    "Cartes microSD",
    "Casque",
    "Casque antibruit",
    "Casque audio",
    "Casque de gaming",
    "Casque de jeu",
    "Casque de moto",
    "Casque de réalité virtuelle",
    "Casque de ski",
    "Casque de vélo",
    "Casque sans fil",
    "Casques DJ",
    "Casques antibruit",
    "Casques audio",
    "Casques audio avec commandes tactiles",
    "Casques audio avec convertisseurs numérique-analogique (DAC)",
    "Casques audio avec personnalisation du son",
    "Casques audio avec personnalisation sonore",
    "Casques audio pliables",
    "Casques audio pliables avec étui de transport",
    "Casques audio à conduction osseuse",
    "Casques audio à isolation phonique",
    "Casques circum-auraux",
    "Casques d'écoute circum-auraux avec DAC intégré",
    "Casques d'écoute ouverts",
    "Casques d'écoute sans fil avec codecs haute résolution",
    "Casques de jeu",
    "Casques de réalité augmentée",
    "Casques de ski",
    "Casques de studio professionnels",
    "Casques de vélo",
    "Casques fermés",
    "Casques gamer",
    "Casques gamer avec rétroéclairage RGB",
    "Casques gamer sans fil",
    "Casques gaming avec son surround",
    "Casques ouverts",
    "Casques ouverts haut de gamme",
    "Casques à réduction de bruit",
    "Casques à réduction de bruit active",
    "Casquette",
    "Casquettes de films",
    "Casserole",
    "Casseroles",
    "Cavalier King Charles",
    "Cavalier King Charles Spaniel",
    "Cave",
    "Cave à cigares",
    "Cave à vin réfrigérée",
    "Chaise",
    "Chaise berçante",
    "Chaise de bureau",
    "Chaise de bureau ergonomique",
    "Chaise de plage pliante",
    "Chaise ergonomique",
    "Chaise haute pliable",
    "Chaise haute évolutive",
    "Chaise pliante",
    "Chalumeau de soudage",
    "Chapeau",
    "Chapeau fedora",
    "Chapeaux en paille guadeloupéens",
    "Chapeaux vintage",
    "Chapman sticks",
    "Chargeur",
    "Chargeur de piles",
    "Chargeur solaire",
    "Chargeurs de batterie pour voiture",
    "Chargeurs de téléphone pour voiture",
    "Chargeurs de téléphone sans fil pour voiture",
    "Chargeurs de voiture",
    "Chargeurs de voiture avec prises USB multiples",
    "Chargeurs sans fil",
    "Chargeurs solaires pour voiture",
    "Chariot de mécanicien",
    "Chariot à outils",
    "Chartreux",
    "Chat",
    "Chaton",
    "Chausse-pied",
    "Chaussettes anti-dérapantes",
    "Chaussons en cuir souple",
    "Chaussons en laine",
    "Chaussures",
    "Chaussures de basket",
    "Chaussures de basketball",
    "Chaussures de course",
    "Chaussures de course à pied",
    "Chaussures de cyclisme",
    "Chaussures de football",
    "Chaussures de football américain",
    "Chaussures de golf",
    "Chaussures de marche",
    "Chaussures de randonnée",
    "Chaussures de running",
    "Chaussures de ski",
    "Chaussures de sport",
    "Chaînes à neige",
    "Chemise",
    "Chemise à carreaux",
    "Chemises pour documents",
    "Chemises pour documents à motifs",
    "Chemises à élastiques",
    "Chemises à élastiques colorées",
    "Chien",
    "Chien de Montagne des Pyrénées",
    "Chiffon",
    "Chihuahua",
    "Chili",
    "Chinchilla",
    "Chine",
    "Chiot",
    "Chow-Chow",
    "Chypre",
    "Chèvre naine",
    "Chœurs virtuels",
    "Cintreuse à ressort",
    "Cintreuse à tube",
    "Circuits d'horloge",
    "Circuits de conversion DC-DC",
    "Circuits de protection contre les surintensités",
    "Circuits de protection contre les surtensions",
    "Circuits intégrés",
    "Circuits intégrés logiques",
    "Cires et gels de coiffage",
    "Cires pour épilation",
    "Ciseaux",
    "Ciseaux de coiffure",
    "Ciseaux de cuisine",
    "Ciseaux ergonomiques",
    "Ciseaux pour ongles",
    "Ciseaux à ongles",
    "Ciseaux à sourcils",
    "Ciseaux à tôle",
    "Cithares",
    "Civilization VI",
    "Clarinettes",
    "Classeurs",
    "Classeurs à anneaux",
    "Clavecins",
    "Clavier",
    "Clavier de jeu",
    "Clavier sans fil",
    "Claviers maîtres MIDI",
    "Claviers mécaniques rétroéclairés",
    "Climatiseur portable",
    "Clé dynamométrique",
    "Clé dynamométrique électronique",
    "Clé plate à cliquet",
    "Clé polygonale",
    "Clé serre-tube",
    "Clé universelle",
    "Clé à bougie à cliquet",
    "Clé à bougies",
    "Clé à choc",
    "Clé à choc pneumatique",
    "Clé à choc électrique",
    "Clé à ergots",
    "Clé à molette",
    "Clé à molette à ouverture rapide",
    "Clé à pipe",
    "Clés USB",
    "Cobaye",
    "Cobra ODE",
    "Cochon d'Inde",
    "Cochon miniature",
    "Cocker Américain",
    "Cocker Spaniel",
    "Cocotte-minute",
    "Coffres de toit",
    "Coffret de maquillage",
    "Coffret de vin",
    "Coffrets de rhum guadeloupéen",
    "ColecoVision",
    "Colle",
    "Colle en bâton",
    "Collier pour chien",
    "Colombie",
    "Combinaisons de natation",
    "Combinaisons de plongée",
    "Combinaisons de surf",
    "Commodore 64",
    "Commuteurs de circuit imprimé",
    "Comores",
    "Compas",
    "Compresseur d'air",
    "Compresseur d'air silencieux",
    "Compresseur portatif",
    "Compteurs d'énergie",
    "Condensateurs",
    "Condensateurs céramiques",
    "Condensateurs céramiques multicouches",
    "Condensateurs de découplage",
    "Condensateurs film",
    "Condensateurs tantale",
    "Condensateurs à diélectrique polymère",
    "Condensateurs à film polyester",
    "Condensateurs électrolytiques",
    "Condensateurs électrolytiques en aluminium",
    "Congo",
    "Connecteurs de carte de circuit imprimé",
    "Console",
    "Console de jeux",
    "Console de jeux vidéo",
    "Console portable",
    "Console rétro",
    "Contraceptifs",
    "Contrôleur de mouvement",
    "Contrôleurs MIDI",
    "Contrôleurs de LED",
    "Contrôleurs de jeu",
    "Contrôleurs de température",
    "Contrôleurs domotiques",
    "Convertisseurs de tension",
    "Cordes à sauter",
    "Cors d'harmonie",
    "Corée du Nord",
    "Corée du Sud",
    "Cosmétiques naturels",
    "Costa Rica",
    "Costume",
    "Costumes et accessoires de films pour cosplay",
    "Costumes élégants",
    "Couchage pour chien",
    "Couches jetables",
    "Couches lavables",
    "Counter-Strike",
    "Counter-Strike: Global Offensive",
    "Counter-Strike: Source",
    "Coupe-ongles",
    "Coupe-papier",
    "Coupes menstruelles",
    "Coussin chauffant",
    "Coussin de chaise",
    "Coussin de méditation",
    "Coussin de voyage",
    "Coussin de yoga",
    "Coussin décoratif",
    "Coussin lombaire",
    "Coussin orthopédique",
    "Coussin orthopédique pour chiens",
    "Coussin pour chat",
    "Coussin pour chien",
    "Coussins de siège de voiture",
    "Couteau de chef",
    "Couteau de poche",
    "Couteau suisse",
    "Couteau à pain",
    "Couteau électrique",
    "Couteaux de cuisine",
    "Couvercles hermétiques",
    "Couverture",
    "Couverture chauffante",
    "Couverture d'extérieur",
    "Couverture en polaire",
    "Couverture pour chien",
    "Couvertures pour pare-brise",
    "Crayon feutre",
    "Crayon à papier",
    "Crayons de couleur",
    "Crayons de couleur aquarellables",
    "Crayons de plomb",
    "Crayons feutres à double pointe",
    "Crayons mécaniques",
    "Crayons mécaniques rechargeables",
    "Crayons à papier",
    "Cric hydraulique",
    "Cristaux oscillateurs",
    "Croatie",
    "Croquettes pour chats",
    "Crème hydratante",
    "Crèmes dépilatoires",
    "Crèmes hydratantes pour le visage",
    "Crèmes pour le cou et le décolleté",
    "Crémaillère de direction",
    "Cuba",
    "Cuillères en bois",
    "Cuiseur sous pression",
    "Cuiseur à riz",
    "Cuiseur à vapeur",
    "Cuiseur à œufs",
    "Cuisinière",
    "Cuphead",
    "Custom Firmware",
    "Câble Ethernet",
    "Câble HDMI",
    "Câble USB-C",
    "Câble audio",
    "Câble de charge USB",
    "Câble de charge rapide",
    "Câble de chargeur de voiture",
    "Câble de recharge",
    "Câble de recharge rapide",
    "Câble micro USB",
    "Câbles DisplayPort",
    "Câbles Ethernet",
    "Câbles Ethernet haute vitesse",
    "Câbles HDMI",
    "Câbles HDMI haute vitesse",
    "Câbles USB",
    "Câbles USB-C",
    "Câbles VGA",
    "Câbles adaptateurs OBD-II",
    "Câbles adaptateurs pour autoradio",
    "Câbles adaptateurs pour téléphone et voiture",
    "Câbles audio",
    "Câbles coaxiaux",
    "Câbles d'alimentation",
    "Câbles de charge USB pour voiture",
    "Câbles de charge magnétiques",
    "Câbles de données",
    "Câbles de démarrage",
    "Câbles de démarrage avec protection contre les surtensions",
    "Câbles de programmation",
    "Câbles de recharge magnétiques",
    "Câbles optiques",
    "Céramiques et poteries inspirées de la Guadeloupe",
    "Côte d'Ivoire",
    "DOOM 64",
    "DVD et Blu-ray",
    "DVD et musique zouk guadeloupéens",
    "DVDs de classiques du cinéma",
    "Dalmatien",
    "Dance Dance Revolution Pad",
    "Dance Pad",
    "Danemark",
    "Dark Souls",
    "Dark Souls II",
    "Dark Souls III",
    "Dark Souls III: Ashes of Ariandel",
    "Dark Souls Remastered",
    "Dark Souls: Prepare to Die Edition",
    "Dessoudeur",
    "Destiny 2",
    "Diablo II",
    "Diablo III",
    "Diablo III: Eternal Collection",
    "Diablo III: Reaper of Souls",
    "Dictionnaires",
    "Dictionnaires et thésaurus en ligne",
    "Didgeridoos",
    "Diffuseur de lumière",
    "Diffuseurs d'arômes pour voiture",
    "Diffuseurs de parfum pour voiture",
    "Diodes",
    "Diodes PIN",
    "Diodes Schottky",
    "Diodes TVS",
    "Diodes Zener",
    "Diodes de redressement",
    "Diodes laser",
    "Diodes électroluminescentes (LED)",
    "Diodes électroluminescentes haute puissance",
    "Disque dur externe",
    "Disques durs externes",
    "Disques durs réseau (NAS)",
    "Distributeur de croquettes automatique",
    "Distributeur de friandises pour chiens",
    "Djibouti",
    "Dominique",
    "Doom",
    "Doom (2016)",
    "Doom Eternal",
    "Doseurs",
    "Doudou musical",
    "Doudou tout doux",
    "Doudou à mâchouiller",
    "Douille de clé",
    "Douille longue à choc",
    "Douille à choc",
    "Dragon Age: Inquisition",
    "Drapeau Bosnie & Herzegovine",
    "Drapeau Guadeloupe",
    "Drapeau Martinique",
    "Drapeau d'Israël",
    "Drapeau de Singapour",
    "Drapeau de Taïwan",
    "Drapeau de l'Afghanistan",
    "Drapeau de l'Afrique du Sud",
    "Drapeau de l'Algérie",
    "Drapeau de l'Allemagne",
    "Drapeau de l'Arabie saoudite",
    "Drapeau de l'Argentine",
    "Drapeau de l'Australie",
    "Drapeau de l'Autriche",
    "Drapeau de l'Espagne",
    "Drapeau de l'Inde",
    "Drapeau de l'Indonésie",
    "Drapeau de l'Irak",
    "Drapeau de l'Iran",
    "Drapeau de l'Irlande",
    "Drapeau de l'Israël",
    "Drapeau de l'Italie",
    "Drapeau de l'Ouganda",
    "Drapeau de l'Ukraine",
    "Drapeau de l'Uruguay",
    "Drapeau de l'Égypte",
    "Drapeau de l'Éthiopie",
    "Drapeau de la Belgique",
    "Drapeau de la Chine",
    "Drapeau de la Colombie",
    "Drapeau de la Corée du Nord",
    "Drapeau de la Corée du Sud",
    "Drapeau de la Finlande",
    "Drapeau de la France",
    "Drapeau de la Grèce",
    "Drapeau de la Hongrie",
    "Drapeau de la Jordanie",
    "Drapeau de la Malaisie",
    "Drapeau de la Norvège",
    "Drapeau de la Nouvelle-Zélande",
    "Drapeau de la Pologne",
    "Drapeau de la Russie",
    "Drapeau de la Suisse",
    "Drapeau de la Suède",
    "Drapeau de la Thaïlande",
    "Drapeau de la Tunisie",
    "Drapeau de la Turquie",
    "Drapeau des Pays-Bas",
    "Drapeau des Philippines",
    "Drapeau des États-Unis",
    "Drapeau du Brésil",
    "Drapeau du Canada",
    "Drapeau du Chili",
    "Drapeau du Danemark",
    "Drapeau du Japon",
    "Drapeau du Kenya",
    "Drapeau du Maroc",
    "Drapeau du Mexique",
    "Drapeau du Nigeria",
    "Drapeau du Pakistan",
    "Drapeau du Portugal",
    "Drapeau du Pérou",
    "Drapeau du Royaume-Uni",
    "Drapeau du Venezuela",
    "Drapeau du Vietnam",
    "Drapeaux",
    "Drone",
    "Drone de course",
    "Drone quadricoptère",
    "Drum Kit Controller",
    "DualSense",
    "DualShock",
    "Dulcimers",
    "Décolle-pneu",
    "Déflecteurs d'air de fenêtre",
    "Déflecteurs de pluie",
    "Défrisants capillaires",
    "Dégrippant",
    "Démaquillants",
    "Démaquillants pour les yeux",
    "Démarreurs à distance",
    "Dénoyauteurs",
    "Déodorants",
    "Déshumidificateurs pour voiture",
    "Déshydrateur alimentaire",
    "Détecteur de métaux",
    "Détecteurs de fumée intelligents",
    "Détecteurs de mouvement",
    "Echarpe de portage",
    "Ecureuil de Corée",
    "Emulator",
    "Enceinte",
    "Enceinte Bluetooth",
    "Enceinte intelligente",
    "Enceintes Bluetooth",
    "Enceintes Bluetooth avec assistant vocal intégré",
    "Enceintes Bluetooth avec fonction de charge sans fil",
    "Enceintes Bluetooth avec éclairage LED",
    "Enceintes amplifiées",
    "Enceintes colonne",
    "Enceintes de bibliothèque pour audiophiles",
    "Enceintes de cinéma maison",
    "Enceintes de monitoring",
    "Enceintes de monitoring actives avec calibration",
    "Enceintes de monitoring de studio",
    "Enceintes de sono",
    "Enceintes de sono actives",
    "Enceintes de sono avec connectivité sans fil",
    "Enceintes intelligentes avec assistants vocaux",
    "Enceintes intelligentes avec écran",
    "Enceintes multiroom",
    "Enceintes portables",
    "Enceintes portables avec effets lumineux",
    "Enceintes portables avec fonctions de karaoké",
    "Enceintes portables avec étanchéité IP67",
    "Enceintes portables étanches",
    "Enceintes pour home cinéma",
    "Enceintes pour ordinateur",
    "Enceintes pour ordinateur avec radiateurs passifs",
    "Enceintes pour tableau de bord",
    "Enceintes pour voiture",
    "Enceintes sans fil avec connectivité multiroom",
    "Enceintes sans fil multiroom",
    "Enceintes surround",
    "Enclos extérieur pour lapins",
    "Enclos pour lapin",
    "Enclos pour rongeurs",
    "Enjoliveurs",
    "Enregistreur",
    "Enregistreur audio",
    "Enregistreur vocal numérique",
    "Enregistreurs audio",
    "Enregistreurs audio multipistes",
    "Enregistreurs audio portables",
    "Enregistreurs vidéo réseau (NVR)",
    "Enregistreurs vocaux numériques",
    "Enrouleurs de ceinture de sécurité",
    "Ensemble de bagages",
    "Ensemble de couteaux de cuisine",
    "Ensemble de couverts",
    "Ensembles de couverts",
    "Equipements de crossfit",
    "Equipements de musculation",
    "Equipements de sports nautiques",
    "Espagne",
    "Essoreuses à salade",
    "Essuie-tout réutilisables",
    "Estonie",
    "Eswatini",
    "Euphoniums",
    "Exfoliants pour le visage",
    "Exotic Shorthair",
    "Expansion Pak",
    "Extensions de cils",
    "Extracteur de jus",
    "Extracteur de roulement",
    "Extracteur de vis",
    "FIFA 22",
    "Fallout 4",
    "Fer",
    "Fer à boucler",
    "Fer à lisser",
    "Fer à lisser professionnel",
    "Fer à repasser",
    "Fer à repasser à vapeur",
    "Fer à souder",
    "Fers à friser",
    "Fers à friser automatiques",
    "Fers à lisser et à boucler",
    "Fers à souder de précision",
    "Feuilles de papier",
    "Feuilles de papier lignées",
    "Feutres",
    "Feutres à pointe fine",
    "Fidji",
    "Fighting Game Pad",
    "Fightstick",
    "Fil de soudure de faible diamètre",
    "Fil à souder",
    "Filet de protection pour balcon pour chats",
    "Filet de sécurité pour chat",
    "Filets de coffre",
    "Films érotiques",
    "Fils de liaison",
    "Filtres à air",
    "Filtres à huile",
    "Final Fantasy IX",
    "Final Fantasy VII",
    "Final Fantasy X",
    "Final Fantasy XII",
    "Final Fantasy XV",
    "Finlande",
    "Fishing Rod Controller",
    "Flashcart",
    "Flight Stick",
    "Flux de soudure",
    "Flûtes de pan",
    "Flûtes traversières",
    "Flûtes à bec",
    "Fontaine à eau filtrante pour chats",
    "Fontaine à eau pour animaux",
    "Foret hélicoïdal en titane",
    "Fortnite",
    "Forza Horizon 3",
    "Forza Horizon 4",
    "Forza Horizon 5",
    "Forza Motorsport 7",
    "Fouets",
    "Four à convection",
    "Four à micro-ondes",
    "Fourchette",
    "France",
    "Freeshop",
    "Friteuse",
    "Friteuse électrique",
    "Furet",
    "Fursuit",
    "Fusibles électroniques",
    "Fusée Gelée",
    "GPS",
    "Gabarit de perçage",
    "Gabon",
    "Gadgets pour le télétravail",
    "Gambie",
    "Game Boy",
    "Game Boy Advance",
    "Game Boy Color",
    "Game Boy Player",
    "Game Genie",
    "GameCube Controller",
    "GameCube Swiss",
    "GameShark",
    "Gamelle anti-glouton pour chiens",
    "Gamelle pour chat",
    "Gamepad Attachment",
    "Gants ESD",
    "Gants de boxe",
    "Gants de conduite",
    "Gants de cuisine",
    "Gants de cyclisme",
    "Gants de fitness",
    "Gants de gardien de but",
    "Gants de golf",
    "Gants de jardinage",
    "Gants de vélo",
    "Gateway 3DS",
    "Gears of War",
    "Gears of War 2",
    "Gears of War 3",
    "Gears of War 4",
    "Gel stimulant",
    "Gels coiffants",
    "Gels nettoyants pour le visage",
    "Gels raffermissants",
    "Gerbille",
    "Ghana",
    "Gigoteuse douillette",
    "Gigoteuse légère",
    "Gilets de protection pour sports extrêmes",
    "Gilets de sauvetage",
    "Glacières électriques pour voiture",
    "Globe terrestre",
    "Globes terrestres interactifs",
    "Glockenspiels",
    "Gobelet",
    "God of War",
    "God of War (2018)",
    "God of War II",
    "God of War III",
    "Gode",
    "Golden Retriever",
    "Gommages pour le corps",
    "Gommages pour les lèvres",
    "Gommes ESD",
    "Gommes à effacer",
    "Gonfleurs de pneus",
    "Gonfleurs de pneus portatifs",
    "Google Stadia",
    "Gourde pour chiens",
    "Graines",
    "Graines biologiques",
    "Graines pour oiseaux",
    "Graines rares",
    "Graisseur manuel",
    "Graisseur pneumatique",
    "Grand Theft Auto IV",
    "Grand Theft Auto V",
    "Grand Theft Auto: San Andreas",
    "Grand Theft Auto: Vice City",
    "Grattoir pour chats",
    "Grattoirs à glace",
    "Grenade",
    "Griffoir pour chats",
    "Griffon bruxellois",
    "Gril électrique",
    "Grill électrique",
    "Grille-pain",
    "Grilles de refroidissement",
    "Grèce",
    "Guatemala",
    "Guides de voyage sur la Guadeloupe",
    "Guinée",
    "Guinée équatoriale",
    "Guinée-Bissau",
    "Guitar Controller",
    "Guitar Hero Controller",
    "Guitare acoustique",
    "Guitare électrique",
    "Guitares acoustiques",
    "Guitares électriques",
    "Guyana",
    "Géorgie",
    "HENkaku Enso",
    "HTC Vive",
    "Hachoir",
    "Hachoir à viande",
    "Hacking Tool",
    "Half-Life",
    "Half-Life 2",
    "Half-Life 2: Episode One",
    "Half-Life 2: Episode Two",
    "Halo 2",
    "Halo 3",
    "Halo: Combat Evolved",
    "Halo: Reach",
    "Haltères",
    "Haltères ajustables",
    "Haltères en fonte",
    "Haltères en néoprène",
    "Haltères réglables",
    "Hamac",
    "Hamac pour chats",
    "Hamacster",
    "Hamster",
    "Hang drums",
    "Hardmod",
    "Harmonicas",
    "Harmoniums",
    "Harnais pour chat",
    "Harpes",
    "Haut-parleur Bluetooth",
    "Haut-parleur portable",
    "Haut-parleurs",
    "Haut-parleurs de jeu",
    "Haut-parleurs hi-fi",
    "Haut-parleurs sans fil",
    "Hautbois",
    "Haïti",
    "Hekate",
    "Himalayen",
    "Hochet coloré",
    "Homebrew Launcher",
    "Honduras",
    "Hongrie",
    "Horizon Zero Dawn",
    "Housses de protection pour moto",
    "Housses de protection pour pneus",
    "Housses de protection pour sièges d'auto pour enfants",
    "Housses de protection pour voiture",
    "Housses de rétroviseur",
    "Housses de siège",
    "Housses de siège en cuir",
    "Housses de siège pour animaux de compagnie",
    "Housses de volant",
    "Housses de volant chauffantes",
    "Housses de volant en cuir",
    "Housses de volant en gel",
    "Housses de volant ergonomiques",
    "Huile moteur",
    "Huiles de massage",
    "Husky Sibérien",
    "Hérisson",
    "Iguane",
    "Imprimante",
    "Imprimante 3D",
    "Imprimante laser",
    "Imprimantes 3D",
    "Inde",
    "Indonésie",
    "Inductances",
    "Infuseurs à thé",
    "Instruments de musique",
    "Instruments de musique traditionnels guadeloupéens",
    "Intellivision",
    "Intercalaires",
    "Intercalaires plastifiés",
    "Interrupteurs intelligents",
    "Interrupteurs variateurs",
    "Irak",
    "Iran",
    "Irlande",
    "Islande",
    "Israël",
    "Italie",
    "JRunner",
    "Jack Russell Terrier",
    "Jailbreak",
    "Jamaïque",
    "Japon",
    "Jeu d'échecs",
    "Jeu de backgammon",
    "Jeu de cartes",
    "Jeu de clés Allen",
    "Jeu de dominos",
    "Jeu de douilles",
    "Jeu de douilles longues",
    "Jeu de fléchettes",
    "Jeu de fléchettes magnétiques",
    "Jeu de forets",
    "Jeu de forets cobalt",
    "Jeu de forets à cobalt",
    "Jeu de limes",
    "Jeu de pétanque",
    "Jeu de raquettes",
    "Jeu de société",
    "Jeu de société pour enfants",
    "Jeu de tournevis de précision",
    "Jeu de tournevis à frapper",
    "Jeux",
    "Jeux de société basés sur des films",
    "Jeux de société stratégiques",
    "Jig RCM",
    "Jordanie",
    "Jouet d'éveil en bois",
    "Jouet de dentition réfrigérant",
    "Jouet en caoutchouc",
    "Jouet interactif pour chat",
    "Jouet interactif pour chien",
    "Jouet interactif pour rongeurs",
    "Jouet pour chien",
    "Jouet pour oiseaux",
    "Jouet à mâcher pour chiens",
    "Jouets pour enfants",
    "Jouhikko",
    "Joy-Con",
    "Joystick",
    "Jumelles",
    "Jumelles à vision nocturne",
    "Kalebas",
    "Kazakhstan",
    "Kazoos",
    "Kenya",
    "Kinect Sensor",
    "Kingdom Hearts",
    "Kingdom Hearts II",
    "Kingdom Hearts III",
    "Kirghizistan",
    "Kiribati",
    "Kit d'outils électroniques",
    "Kit de composants électroniques",
    "Kit de débosselage sans peinture",
    "Kit de nettoyage de carrosserie",
    "Kit de réparation de filetage",
    "Kit de réparation de pneus",
    "Kit de réparation pneumatique",
    "Kit de soins pour barbe",
    "Kit mains libres Bluetooth",
    "Kits d'enceintes DIY",
    "Kits d'éclairage intérieur LED",
    "Kits d'éclairage pour plaque d'immatriculation",
    "Kits de basketball",
    "Kits de boxe",
    "Kits de camping",
    "Kits de câblage",
    "Kits de fitness",
    "Kits de musculation à domicile",
    "Kits de nettoyage de carrosserie",
    "Kits de nettoyage de cuir pour voiture",
    "Kits de nettoyage de jantes",
    "Kits de nettoyage de tapis de voiture",
    "Kits de nettoyage extérieur pour voiture",
    "Kits de nettoyage intérieur et extérieur pour voiture",
    "Kits de nettoyage intérieur pour voiture",
    "Kits de polissage de voiture",
    "Kits de premiers secours pour voiture",
    "Kits de protection de peinture",
    "Kits de restauration de cuir pour voiture",
    "Kits de restauration de phares",
    "Kits de restauration de plastique pour voiture",
    "Kits de réparation d'ordinateurs portables",
    "Kits de réparation d'éclat de pare-brise",
    "Kits de réparation de pneus",
    "Kits de réparation de smartphones",
    "Kits de réparation de téléphone portable",
    "Kotos",
    "Koweït",
    "L-DEV31 Salut c'est moi",
    "Labrador",
    "Laisse pour chien",
    "Lampe",
    "Lampe UV",
    "Lampe de bureau à LED",
    "Lampe de poche",
    "Lampe de travail LED",
    "Lampe frontale",
    "Lampe frontale à LED",
    "Lampe torche",
    "Lampe veilleuse",
    "Lampe veilleuse étoilée",
    "Laos",
    "Lapin nain",
    "Laptop",
    "Lave-linge",
    "Lecteur de musique MP3",
    "Lecteur eBook",
    "Lecteurs de cartes mémoire",
    "Lesotho",
    "Lettonie",
    "Liban",
    "Liberia",
    "Libye",
    "Liechtenstein",
    "Light Gun",
    "Lingettes démaquillantes",
    "Link Cable",
    "Lit",
    "Lit escamotable",
    "Lit parapluie pratique",
    "Lit évolutif",
    "Litière pour chat",
    "Litière pour chat écologique",
    "Lituanie",
    "Livre de coloriage pour adultes",
    "Livre de contes",
    "Livre de poche",
    "Livre électronique",
    "Livres",
    "Livres de cuisine internationale",
    "Livres de développement personnel",
    "Livres en tissu",
    "Livres sur l'histoire du cinéma",
    "Livres sur la Guadeloupe",
    "Lotions autobronzantes",
    "Lotions pour le corps",
    "Loupes électroniques",
    "Lubrifiants intimes",
    "Luma3DS",
    "Lunettes anti-lumière bleue",
    "Lunettes de conduite de nuit",
    "Lunettes de lecture",
    "Lunettes de natation",
    "Lunettes de réalité augmentée",
    "Lunettes de réalité virtuelle",
    "Lunettes de soleil",
    "Lunettes de soleil polarisées",
    "Luths",
    "Luxembourg",
    "Lève-moteur",
    "Lézard domestique",
    "MSX",
    "Machine à barbe à papa",
    "Machine à biscuits",
    "Machine à café",
    "Machine à café automatique",
    "Machine à chocolat chaud",
    "Machine à coudre",
    "Machine à croque-monsieur",
    "Machine à crème glacée",
    "Machine à crêpes",
    "Machine à espresso",
    "Machine à fondue",
    "Machine à gaufres",
    "Machine à glace",
    "Machine à hot-dogs",
    "Machine à jus",
    "Machine à laver la vaisselle",
    "Machine à pain",
    "Machine à pop-corn",
    "Machine à pâtes",
    "Machine à smoothie",
    "Machine à sous-vide",
    "Machine à takoyaki",
    "Machine à yaourts",
    "Macédoine du Nord",
    "Madagascar",
    "Maillot",
    "Maillot de bain",
    "Maillots de bain de compétition",
    "Maillots de cyclisme",
    "Maillots de football",
    "Maillots de football américain",
    "Maillots de sport",
    "Maillots de vélo",
    "Maine Coon",
    "Maison en bois pour lapin",
    "Maison en carton pour chats",
    "Maisonnette pour rongeurs",
    "Malaisie",
    "Malawi",
    "Maldives",
    "Malette de maquillage",
    "Mali",
    "Mallette à outils",
    "Malte",
    "Mandoline",
    "Manette PlayStation",
    "Manette Pro Switch",
    "Manette Xbox",
    "Manette Xbox Elite",
    "Manette de jeu",
    "Manette filaire",
    "Manette sans fil",
    "Mangeoire automatique pour oiseaux",
    "Mangeoire pour oiseaux",
    "Manteau d'hiver",
    "Manuels scolaires",
    "Manuels scolaires en version numérique",
    "Manx",
    "Maquettes de vaisseaux spatiaux de films de science-fiction",
    "Maquillage",
    "Maquillage de qualité professionnelle",
    "Maracas",
    "Marbre de mesure",
    "Marimbas",
    "Mario Kart 7",
    "Mario Kart 8",
    "Mario Kart 8 Deluxe",
    "Maroc",
    "Marqueurs",
    "Marqueurs effaçables à sec",
    "Marteau",
    "Marteau perforateur",
    "Marteau à inertie",
    "Martinet de carrossier",
    "Mascara",
    "Masques capillaires",
    "Masques de beauté",
    "Masques de protection pour micro soudure",
    "Masques de sommeil et masques pour les yeux",
    "Mass Effect",
    "Mass Effect 2",
    "Mass Effect 3",
    "Mass Effect: Andromeda",
    "Mass Effect: Legendary Edition",
    "Massages sensuels",
    "Mastiff",
    "Matelas",
    "Matelas de gym",
    "Matelas en mousse à mémoire de forme",
    "Matelas gonflable",
    "Matelas orthopédique",
    "Matelas à langer",
    "Matériel de musculation",
    "Matériel de plongée",
    "Maurice",
    "Mauritanie",
    "Memory Card",
    "Metal Gear Solid",
    "Metal Gear Solid 2: Sons of Liberty",
    "Metal Gear Solid 3: Snake Eater",
    "Metal Gear Solid V: The Phantom Pain",
    "Meubles",
    "Meubles de jardin",
    "Meubles en bambou",
    "Meubles en rotin",
    "Mexique",
    "Microcontrôleurs",
    "Microcontrôleurs AVR",
    "Micronésie",
    "Microphone Controller",
    "Microphone USB",
    "Microphone de jeu",
    "Microphones",
    "Microphones USB",
    "Microphones USB avec bras articulé",
    "Microphones USB avec réduction de bruit",
    "Microphones USB avec réglage de la directivité",
    "Microphones USB avec élimination du bruit de fond",
    "Microphones cravate",
    "Microphones cravate sans fil",
    "Microphones de studio à grand diaphragme",
    "Microphones dynamiques",
    "Microphones dynamiques pour la scène",
    "Microphones lavalier sans fil",
    "Microphones pour podcast avec filtre anti-pop",
    "Microphones shotgun",
    "Microphones shotgun directionnels",
    "Microphones à condensateur",
    "Microphones à condensateur USB",
    "Microphones à condensateur avec antichoc",
    "Microphones à pince",
    "Microphones à pince avec atténuateur",
    "Microphones à pince à col de cygne",
    "Microphones à ruban",
    "Microphones à ruban pour enregistrement vintage",
    "Microphones à électret pour enregistrement mobile",
    "Microscope",
    "Microscopes de soudure",
    "Minecraft",
    "Mini ventilateur",
    "Mini-réfrigérateur",
    "Minuteur",
    "Miroir grossissant",
    "Mixer",
    "Mixeur plongeant",
    "Mixeur à immersion",
    "Mixeurs",
    "Mobile en bois",
    "Mobile en tissu",
    "Mobile musical",
    "Mobile musical à projection",
    "Mobile à accrocher",
    "Mobile à suspendre",
    "Modchip",
    "Modules Arduino",
    "Modules Bluetooth",
    "Modules GPS",
    "Modules NFC",
    "Modules RFID",
    "Modules Raspberry Pi",
    "Modules Wi-Fi",
    "Modules de capteurs environnementaux",
    "Modules relais",
    "Moldavie",
    "Monaco",
    "Mongolie",
    "Moniteur",
    "Moniteur bébé",
    "Moniteur incurvé",
    "Moniteur vidéo bébé",
    "Moniteurs de studio",
    "Moniteurs incurvés",
    "Montre",
    "Montre automatique",
    "Montre chronographe",
    "Montre connectée",
    "Monténégro",
    "Mortal Kombat X",
    "Motion Controller",
    "MotionPlus",
    "Moule à glaçons",
    "Moule à gâteau",
    "Moules à glaçons",
    "Moules à gâteaux",
    "Moules à muffins",
    "Moules à pizza",
    "Moules à pâtes",
    "Moules à tartes",
    "Moulin à café",
    "Moulin à graines",
    "Moulin à poivre",
    "Moulin à sel",
    "Moulin à sel et poivre électrique",
    "Moulin à épices",
    "Mousses de coiffage",
    "Mozambique",
    "MultiMAN",
    "Multimètre",
    "Multitap",
    "Munchkin",
    "Mètre ruban",
    "Mètre ruban professionnel",
    "Mélodicas",
    "Mémoires flash",
    "NAND Dump",
    "NES Advantage",
    "Namibie",
    "Nauru",
    "Neo Geo",
    "Nettoyants intimes",
    "Nettoyants pour vitres",
    "Nicaragua",
    "Niche pour chien",
    "Nid pour oiseaux",
    "Nier: Automata",
    "Niger",
    "Nigeria",
    "Nintendo 3DS",
    "Nintendo 64",
    "Nintendo 64 Controller",
    "Nintendo DS",
    "Nintendo DSi",
    "Nintendo Entertainment System (NES)",
    "Nintendo GameCube",
    "Nintendo Labo",
    "Nintendo Switch",
    "Switch",
    "Nintendont",
    "Niue",
    "Niveau laser",
    "Niveau laser rotatif",
    "Niveau à bulle",
    "Norvège",
    "Nouvelle-Zélande",
    "Nunchuk",
    "Nyckelharpa",
    "Népal",
    "Objets",
    "Objets d'art en bois guadeloupéens",
    "Objets de domotique intelligents",
    "Ocarinas",
    "Octodon",
    "Oculus Quest",
    "Oculus Rift",
    "Oculus Touch",
    "Odyssey",
    "Oiseau exotique",
    "Oman",
    "Optocoupleurs",
    "Optocoupleurs à transistor",
    "Ordinateur de bureau",
    "Ordinateur portable",
    "Ordinateur portable avec stylet",
    "Organiseurs de siège arrière",
    "Orgues électroniques",
    "Oscilloscope",
    "Ouds",
    "Ouganda",
    "Outil de calage moteur",
    "Outil de contrôle de géométrie",
    "Outil de pose de rivets",
    "Outil de réglage de soupape",
    "Outils de bricolage",
    "Outils de dépannage électronique",
    "Outils de menuiserie",
    "Outils de réparation électronique",
    "Outils de sertissage",
    "Ouvre-bouteilles de vin",
    "Ouvre-boîtes",
    "Ouya",
    "Ouzbékistan",
    "Overwatch",
    "Oxymètre",
    "Oxymètre de pouls",
    "PS Vita",
    "PS Vita Henkaku",
    "PS1",
    "PS2",
    "PS2 FreeMCBoot",
    "PS3",
    "PS3 CFW",
    "PS4",
    "PS4 Exploit",
    "PS5",
    "PS5 Jailbreak",
    "PSP",
    "PSP (PlayStation Portable)",
    "PSP Custom Firmware",
    "Packs de piles rechargeables",
    "Pakistan",
    "Palan manuel",
    "Palan à chaîne",
    "Palaos",
    "Palestine",
    "Palette",
    "Palette de maquillage",
    "Palette de maquillage bio",
    "Palette de maquillage minéral",
    "Panama",
    "Paniers vapeur",
    "Panne pour fer à souder",
    "Panneaux solaires portables",
    "Pannes de soudure fines",
    "Papier cadeau",
    "Papier calque",
    "Papier millimétré",
    "Papier quadrillé",
    "Papiers calques colorés",
    "Papouasie-Nouvelle-Guinée",
    "Paraguay",
    "Parasol",
    "Parasol chauffant",
    "Parasol de plage",
    "Parc d'extérieur pour chiens",
    "Parc de jeu sécurisé",
    "Parc pliable",
    "Parcours d'agilité pour chiens",
    "Pare-chocs de parking",
    "Pare-soleil pour voiture",
    "Pare-soleils",
    "Pare-soleils pour pare-brise",
    "Parfum",
    "Parfum boisé",
    "Parfum de luxe",
    "Parfum floral",
    "Parfums",
    "Parure de lit bébé",
    "Passoires",
    "Patée pour chiens",
    "Payload Injector",
    "Pays-Bas",
    "Pedalboard",
    "Peignes et brosses pour cheveux",
    "Peintures",
    "Peintures et art guadeloupéen",
    "Peintures à l'huile",
    "Pelle pliante",
    "Peluche câline",
    "Peluche musicale",
    "Peluche sensorielle",
    "Pendule murale",
    "Perceuse sans fil",
    "Perceuse à colonne",
    "Perceuse électrique",
    "Perchoir chauffant pour oiseaux",
    "Perchoir pour oiseaux",
    "Percussions",
    "Percussions électroniques",
    "Perroquet",
    "Perruche",
    "Perruche ondulée",
    "Perruque pour chiens",
    "Persan",
    "Persona 4 Golden",
    "Persona 5",
    "Persona 5 Royal",
    "Philippines",
    "Photographies de plateau de films",
    "Photographies et affiches de paysages guadeloupéens",
    "Piano numérique",
    "Piano à queue",
    "Piano à queue électrique",
    "Pianos numériques",
    "Pied à coulisse",
    "Pied à coulisse digital",
    "Piles alcalines",
    "Piles rechargeables",
    "Pince coupe-câble",
    "Pince de frein",
    "Pince multiprise",
    "Pince multiprise verrouillable",
    "Pince à becs",
    "Pince à becs demi-ronds",
    "Pince à circlips",
    "Pince à riveter",
    "Pince à sertir",
    "Pince étau",
    "Pinceau de maquillage",
    "Pinceaux",
    "Pinceaux de cuisine",
    "Pinceaux de maquillage spécialisés",
    "Pinceaux pour les sourcils",
    "Pinceaux à maquillage",
    "Pinceaux à réservoir d'eau",
    "Pinces de précision",
    "Pinces à becs fins",
    "Piscine gonflable",
    "Piscine pour chiens",
    "Pistolet de débosselage",
    "Pistolet de graissage",
    "Pistolet de peinture",
    "Pistolet de sablage",
    "Pistolet thermique",
    "Pistolet à air chaud",
    "Pistolet à clous",
    "Pistolet à colle",
    "Pistolet à graisse",
    "Plancha électrique",
    "Planche de paddle",
    "Planche de surf",
    "Planche à découper",
    "Planche à découper en bambou",
    "Planche à découper en bois",
    "Planche à découper en plastique",
    "Planche à repasser",
    "Planche à roulettes",
    "Planches à découper colorées",
    "Planchette à découper",
    "Plantes",
    "Plantes d'air",
    "Plantes succulentes",
    "Plaque chauffante",
    "Plaque chauffante pour reptiles",
    "Plaque de cuisson à gaz",
    "Plaque de cuisson à gaz portable",
    "Plaque de cuisson à induction",
    "Plaque de cuisson électrique",
    "Plaque à induction",
    "Plaque à induction portative",
    "Plaque à pâtisserie",
    "Plaques de prototypage",
    "Plat de cuisson en céramique",
    "Platine vinyle",
    "Platines vinyles",
    "Plats de cuisson",
    "PlayStation",
    "PlayStation 2",
    "PlayStation 3",
    "PlayStation 4",
    "PlayStation 5",
    "PlayStation Move",
    "Pneus",
    "Pochettes de plastification",
    "Pochettes plastiques",
    "Pochettes plastiques perforées",
    "Poisson rouge",
    "Pokemon Red and Blue",
    "Pologne",
    "Pommeaux de levier de vitesses",
    "Pompe à graisse pneumatique",
    "Pompe à vélo",
    "Pompes à air portatives",
    "Popcorn pour micro-ondes",
    "Porte Drapeaux",
    "Porte-bijoux",
    "Porte-bouteilles",
    "Porte-bébé",
    "Porte-bébé en écharpe",
    "Porte-bébé ergonomique",
    "Porte-carte professionnel",
    "Porte-cartes RFID",
    "Porte-clés",
    "Porte-clés de personnages de films",
    "Porte-couteaux",
    "Porte-crayons",
    "Porte-gobelets pour voiture",
    "Porte-manteau",
    "Porte-manteau mural",
    "Porte-parapluie",
    "Porte-parapluie mural",
    "Porte-revues",
    "Porte-serviettes",
    "Porte-tablette pour lit",
    "Porte-vélos",
    "Portefeuille",
    "Portugal",
    "Posters de films encadrés",
    "Poteau à gratter pour chats",
    "Poubelle de tri sélectif",
    "Poudres pour cheveux",
    "Poudres pour le visage",
    "Poule",
    "Poussette compacte",
    "Poussette légère",
    "Poussette tout-terrain",
    "Poussette trio",
    "Poussette-canne légère",
    "Poussin",
    "Power Glove",
    "Poêles",
    "Presse d'atelier",
    "Presse hydraulique",
    "Presse hydropneumatique",
    "Presse-agrumes",
    "Presse-agrumes électrique",
    "Presse-fruits",
    "Presse-purée",
    "Prises intelligentes",
    "Prises électriques intelligentes",
    "Produits bio et naturels",
    "Produits cosmétiques à base de fruits tropicaux",
    "Produits de beauté",
    "Produits de coloration des cheveux",
    "Produits de divertissement",
    "Produits de jardinage",
    "Produits de maquillage bio",
    "Produits de nettoyage",
    "Produits de santé",
    "Produits de soin de la peau",
    "Produits de soin des cheveux",
    "Produits de soin des cheveux bouclés",
    "Produits de soin des cils",
    "Produits de soin des coudes et des genoux",
    "Produits de soin des lèvres",
    "Produits de soin des mains",
    "Produits de soin des mains et des pieds",
    "Produits de soin des mains pour hommes",
    "Produits de soin des ongles",
    "Produits de soin des peaux à problèmes",
    "Produits de soin des pieds",
    "Produits de soin des pieds secs",
    "Produits de soin des sourcils",
    "Produits de soin des tatouages",
    "Produits de soin du corps",
    "Produits de soin pour hommes",
    "Produits de soin à base de plantes locales",
    "Produits locaux de cuisine créole",
    "Produits pour animaux de compagnie",
    "Produits pour bébés",
    "Produits pour l'hygiène intime",
    "Produits pour l'hygiène masculine",
    "Produits pour l'épanouissement personnel",
    "Produits pour la fécondité",
    "Produits pour la ménopause",
    "Produits pour la prostate",
    "Produits pour la prévention des infections",
    "Produits pour la santé du sein",
    "Produits pour la santé reproductive",
    "Produits pour la santé sexuelle",
    "Produits pour la santé urinaire",
    "Produits pour la sexualité épanouie",
    "Produits pour la sécheresse vaginale",
    "Produits pour le bain et la douche",
    "Produits pour le bien-être sexuel",
    "Produits pour le blanchiment des dents",
    "Produits pour le confort pendant les règles",
    "Produits pour le contouring",
    "Produits pour le contrôle des odeurs",
    "Produits pour le maquillage des yeux",
    "Produits pour le soutien de la libido",
    "Produits pour les cils",
    "Produits pour les ongles",
    "Produits pour les peaux sensibles",
    "Produits réutilisables",
    "Produits technologiques",
    "Produits textiles de Guadeloupe",
    "Produits zéro déchet",
    "Produits à base de vanille de Guadeloupe",
    "Produits électroniques",
    "Projecteur",
    "Projecteur portable pour présentations",
    "Projecteurs de cinéma maison",
    "Protecteurs de pare-chocs",
    "Protracteurs",
    "Protracteurs en plastique",
    "Protège-slips",
    "Préservatifs",
    "Psalmodies",
    "Puzzle 3D",
    "Puzzle en bois",
    "Puzzles complexes",
    "Pyjama en coton bio",
    "Pâtes à braser",
    "Pèse-bagages",
    "Pèse-personne",
    "Pédalier",
    "Pékinois",
    "Pérou",
    "Qatar",
    "Quenas",
    "R.O.B. the Robot",
    "RCM Loader",
    "RGH",
    "ROM Hack",
    "Racing Seat",
    "Racing Wheel",
    "Radiateur électrique",
    "Radiateurs pour processeurs",
    "Ragamuffin",
    "Ragdoll",
    "Rameur",
    "Rameur d'appartement",
    "Rampe d'escalade pour furet",
    "Rampe pour animaux âgés",
    "Rampes de chargement",
    "Rapporteurs",
    "Rapporteurs transparents",
    "Raquette de badminton",
    "Raquette de beach tennis",
    "Raquette de squash",
    "Raquette de tennis",
    "Raquette de tennis de table",
    "Raquettes de badminton",
    "Raquettes de beach tennis",
    "Raquettes de beach volley",
    "Raquettes de padel",
    "Raquettes de pickleball",
    "Raquettes de racquetball",
    "Raquettes de snowboard",
    "Raquettes de squash",
    "Raquettes de tennis",
    "Raquettes de tennis de table",
    "Rasoir électrique",
    "Rasoirs pour femmes",
    "Rasoirs électriques",
    "Rat domestique",
    "Red Dead Redemption 2",
    "Refroidisseurs pour cartes graphiques",
    "Region-Free Patch",
    "ReiNX",
    "Relais",
    "Resident Evil 2",
    "Resident Evil 4",
    "Resident Evil 5",
    "Resident Evil 7: Biohazard",
    "Rhythm Game Controller",
    "Ring-Con",
    "Riqs",
    "Robe",
    "Robe de soirée",
    "Robot",
    "Robot aspirateur",
    "Robot culinaire",
    "Robot culinaire multifonction",
    "Robot multifonction",
    "Robot nettoyeur de piscine",
    "Robot pâtissier",
    "Robot tondeuse",
    "Rocket League",
    "Rollers",
    "Rollers en ligne",
    "Rottweiler",
    "Rouge à lèvres",
    "Rouges à lèvres",
    "Rouleau de ruban adhésif",
    "Rouleau à pâtisserie",
    "Rouleau à pâtisserie ajustable",
    "Roumanie",
    "Routeur Wi-Fi",
    "Routeurs Wi-Fi mesh",
    "Royaume-Uni",
    "Rubans Kapton",
    "Rumble Pak",
    "Russie",
    "Rwanda",
    "Râpe à fromage",
    "Râpe à légumes",
    "Râpe électrique",
    "Râpes",
    "Règles",
    "Récepteurs AV",
    "Récepteurs Bluetooth",
    "Récepteurs Bluetooth pour autoradio",
    "Réchaud",
    "Réchaud de camping",
    "Récipients de stockage de composants",
    "Réfrigérateur",
    "Réfrigérateur intelligent",
    "Réfrigérateur portable",
    "Régulateurs de courant constant",
    "Régulateurs de tension",
    "Régulateurs de vitesse pour ventilateurs",
    "Régulateurs linéaires",
    "Régulateurs à découpage",
    "Réhausseurs de siège pour enfant",
    "Répliques de sabres laser",
    "République centrafricaine",
    "République dominicaine",
    "République démocratique du Congo",
    "République tchèque",
    "Répulsifs pour animaux pour voiture",
    "Répéteurs Wi-Fi",
    "Réseaux de résistances",
    "Résistances",
    "Résistances de précision",
    "Résistances variables",
    "Résistances à couche épaisse",
    "Résistances à faible température",
    "Résistances à film métallique",
    "Réveil matin",
    "Réveil à projection",
    "SD Card Exploit",
    "SX OS",
    "Sable pour reptiles",
    "Sableuse pneumatique",
    "Sac",
    "Sac de couchage",
    "Sac de golf",
    "Sac de voyage",
    "Sac de voyage à roulettes",
    "Sac isotherme",
    "Sac à dos",
    "Sac à dos anti-vol",
    "Sac à dos de randonnée",
    "Sac à dos étanche",
    "Sac à main",
    "Sacoche d'ordinateur portable",
    "Sacoche de vélo",
    "Sacoche pour batterie externe",
    "Sacré de Birmanie",
    "Sacs de congélation réutilisables",
    "Sacs de rangement pour coffre de voiture",
    "Sacs de rangement pour siège de voiture",
    "Sacs à dos ergonomiques",
    "Saint-Christophe-et-Niévès",
    "Saint-Marin",
    "Saint-Siège",
    "Saint-Vincent-et-les Grenadines",
    "Sainte-Lucie",
    "Saladiers",
    "Salvador",
    "Samoa",
    "Sanza",
    "Savannah",
    "Saxophones",
    "Scanner de documents",
    "Scanners 3D",
    "Schnauzer",
    "Scie",
    "Scie circulaire",
    "Scie sauteuse",
    "Scie à métaux",
    "Scottish Fold",
    "Sega 32X",
    "Sega CD",
    "Sega Dreamcast",
    "Sega Genesis",
    "Sega Genesis (Mega Drive)",
    "Sega Master System",
    "Sega Saturn",
    "Sekiro: Shadows Die Twice",
    "Sels de bain et bombes de bain",
    "Serpent domestique",
    "Serre-joint en C",
    "Serrure à cliquet",
    "Serviettes hygiéniques",
    "Set de badminton",
    "Set de vaisselle adaptée",
    "Set de vaisselle en silicone",
    "Setter Irlandais",
    "Seychelles",
    "Shampooing",
    "Shetland",
    "Shiba Inu",
    "Shih Tzu",
    "Shorts de basketball",
    "Shorts de cyclisme",
    "Shorts de sport",
    "Siamois",
    "Sierra Leone",
    "Singapour",
    "Sitar",
    "Siège auto confortable",
    "Siège auto pivotant",
    "Skateboards",
    "Skateboards électriques",
    "Skis",
    "Skis alpins",
    "Skis de fond",
    "Slovaquie",
    "Slovénie",
    "Smartphone",
    "Smartphone pliable",
    "Sneakers tendance",
    "Softmod",
    "Soins",
    "Soins capillaires biologiques",
    "Soins intimes au naturel",
    "Soins post-accouchement",
    "Somalie",
    "Sonnettes vidéo",
    "Sorbetière",
    "Soudan",
    "Soudan du Sud",
    "Soudeuse à l'arc",
    "Souffleurs d'air chaud",
    "Souris",
    "Souris de jeu",
    "Souris domestique",
    "Souris ergonomique",
    "Souris ergonomiques",
    "Souris sans fil",
    "Souris verticales",
    "Soutiens-gorge d'allaitement",
    "Soutiens-gorge de maternité",
    "Spatules",
    "Sphynx",
    "Splatoon 2",
    "Sprays pour le visage",
    "Sri Lanka",
    "Stadia Controller",
    "Starcraft",
    "Starcraft II",
    "Starcraft II: Wings of Liberty",
    "Station de recharge",
    "Station de soudage",
    "Stations d'accueil pour consoles",
    "Stations d'accueil pour ordinateurs portables",
    "Stations de charge",
    "Stations de micro soudure",
    "Stations de préchauffage",
    "Stations de recharge pour smartphones",
    "Steam Controller",
    "Steam Machine",
    "Steel drums",
    "Steering Wheel",
    "Stickers de films pour ordinateur portable",
    "Stickers personnalisés pour voiture",
    "Stickers pour voiture",
    "String",
    "String dentelle",
    "Stylo gel",
    "Stylo plume",
    "Stylo roller",
    "Stylo à bille",
    "Stylo à pointe fine",
    "Stylo-feutre",
    "Stylos",
    "Stylos 3D",
    "Stylos de flux",
    "Stylos gel de différentes couleurs",
    "Stylos plume",
    "Stylos plume avec motifs",
    "Stylos pour les sourcils",
    "Stylos surligneurs",
    "Stylos surligneurs pastel",
    "Stylos à gel",
    "Stylos à plume",
    "Stylos à plume avec cartouches d'encre",
    "Stylos à pointe fine pour dessin",
    "Stérilisateur de biberons",
    "Stérilisateur à vapeur",
    "Subwoofers",
    "Suisse",
    "Super Mario 3D World",
    "Super Mario 64",
    "Super Mario Bros.",
    "Super Mario Galaxy",
    "Super Mario Galaxy 2",
    "Super Mario Odyssey",
    "Super Mario Sunshine",
    "Super Metroid",
    "Super Nintendo Entertainment System (SNES)",
    "Super Smash Bros. Melee",
    "Super Smash Bros. Ultimate",
    "Support de livre",
    "Support pour fer à souder",
    "Support pour ordinateur portable",
    "Support pour vélo",
    "Supports de carte de circuit imprimé",
    "Supports de tablette pour voiture",
    "Supports de téléphone pour grille de ventilation",
    "Supports de téléphone pour voiture",
    "Supports magnétiques pour téléphone en voiture",
    "Supports pour ordinateurs portables",
    "Suriname",
    "Surligneurs",
    "Surligneurs de différentes couleurs",
    "Survêtements",
    "Survêtements de jogging",
    "Survêtements de sport",
    "Suède",
    "Switch Jailbreak",
    "Synthétiseurs",
    "Syrie",
    "Système",
    "Système d'arrosage automatique",
    "Système d'irrigation goutte à goutte",
    "Systèmes d'alarme pour voiture",
    "Systèmes de sonorisation",
    "São Tomé-et-Principe",
    "Sèche-cheveux ionique",
    "Sèche-cheveux professionnel",
    "Sèche-linge",
    "Sèche-linge à condensation",
    "Sèche-ongles",
    "Sèche-serviette",
    "Sèche-serviettes électrique",
    "Sénégal",
    "Séparateurs LCD",
    "Sérums anti-âge",
    "T-shirts de course",
    "T-shirts de films cultes",
    "T-shirts de gym",
    "T-shirts de sport",
    "T-shirts de sport respirants",
    "TRS-80",
    "Table basse",
    "Table d'appoint",
    "Table de chevet",
    "Table de jardin",
    "Table de jeu",
    "Table de ping-pong",
    "Table de pique-nique",
    "Table de salle à dîner",
    "Table de salle à manger",
    "Table pliable",
    "Table pliante",
    "Table pliante en aluminium",
    "Table pliante en bois",
    "Table pliante en plastique",
    "Table à langer multifonction",
    "Table à manger",
    "Tableaux blancs",
    "Tableaux blancs magnétiques",
    "Tableaux noirs",
    "Tableaux noirs avec craies colorées",
    "Tablette",
    "Tablette graphique",
    "Tablette pour prise de notes",
    "Tablette tactile",
    "Tabliers",
    "Tadjikistan",
    "Taille-crayons",
    "Taille-crayons électrique",
    "Tambours djembé",
    "Tampons hygiéniques",
    "Tanzanie",
    "Tapis",
    "Tapis anti-dérapants pour tableau de bord",
    "Tapis d'éveil coloré",
    "Tapis d'éveil montessori",
    "Tapis d'éveil évolutif",
    "Tapis de coffre",
    "Tapis de course",
    "Tapis de danse",
    "Tapis de plage",
    "Tapis de souris de jeu",
    "Tapis de souris ergonomique",
    "Tapis de voiture",
    "Tapis de yoga",
    "Tapis design",
    "Tapis persan",
    "Tapis rafraîchissant pour chiens",
    "Taraud et filière",
    "Taus",
    "Tchad",
    "Team Xecuter",
    "Teckel",
    "Tensiomètre numérique",
    "Tente",
    "Tente de camping",
    "Tente de randonnée",
    "Tente instantanée",
    "Tente ultralégère",
    "Tenues de cyclisme",
    "Tenues de danse",
    "Tenues de karaté",
    "Terrarium pour reptiles",
    "Test de dépistage IST",
    "Test de grossesse",
    "Testeur de batterie",
    "Testeur de batterie électronique",
    "Testeur de circuit électrique",
    "Testeur de compression",
    "Testeur de compression moteur",
    "Testeur de pression d'huile",
    "Testeur de tension",
    "Tetris",
    "Thaïlande",
    "The Elder Scrolls V: Skyrim",
    "The Last of Us",
    "The Last of Us Part II",
    "The Last of Us: Left Behind",
    "The Last of Us: Part II",
    "The Legend of Zelda: A Link to the Past",
    "The Legend of Zelda: Breath of the Wild",
    "The Legend of Zelda: Link's Awakening",
    "The Legend of Zelda: Majora's Mask",
    "The Legend of Zelda: Minish Cap",
    "The Legend of Zelda: Ocarina of Time",
    "The Legend of Zelda: Oracle of Ages/Seasons",
    "The Legend of Zelda: Skyward Sword",
    "The Legend of Zelda: Tears of the Kingdom",
    "The Legend of Zelda: Twilight Princess",
    "The Legend of Zelda: Wind Waker",
    "The Witcher",
    "The Witcher 2: Assassins of Kings",
    "The Witcher 3: Wild Hunt",
    "Theremins",
    "Thermomètre auriculaire",
    "Thermomètre frontal",
    "Thermomètre infrarouge",
    "Thermomètres alimentaires",
    "Thermos",
    "Thermostats intelligents",
    "Théière en porcelaine",
    "Théorbes",
    "Thérémines",
    "Thésaurus",
    "Timor oriental",
    "Tire-bouchon",
    "Tire-fil électrique",
    "Title Key Site",
    "Togo",
    "Toiles abstraites",
    "Tondeuse à barbe",
    "Tondeuse à cheveux",
    "Tondeuse à gazon",
    "Tondeuse à nez",
    "Tonga",
    "Toniques pour le cuir chevelu",
    "Toniques pour le visage",
    "Tortue terrestre",
    "Touchpad",
    "Tourne-écrou",
    "Tournevis",
    "Tournevis à cliquet",
    "Trackball",
    "Trampoline",
    "Trancheuse à pain",
    "Trancheuse électrique",
    "Transat de plage",
    "Transat en bambou",
    "Transat vibrant",
    "Transformateurs",
    "Transformateurs de signal",
    "Transistors",
    "Transistors MOSFET",
    "Transistors NPN",
    "Transistors bipolaires",
    "Transistors de puissance",
    "Transmetteurs FM",
    "Tresses à dessouder",
    "Trinité-et-Tobago",
    "Trombones",
    "Trompette",
    "Trompettes",
    "Trompettes de poche",
    "Trottinette électrique",
    "Trousse",
    "Trousse de premiers soins",
    "Trousses à compartiments",
    "Tunisie",
    "Tunnel pour chats",
    "Tunnel pour lapin",
    "TurboGrafx-16",
    "TurboGrafx-CD",
    "Turbulette douce",
    "Turbulette légère",
    "Turkménistan",
    "Turquie",
    "Tuvalu",
    "Télécommande universelle",
    "Téléobjectif",
    "Téléphone fixe",
    "Téléviseur",
    "Téléviseur 4K",
    "Téléviseur OLED",
    "Téléviseur QLED",
    "Tétine en silicone",
    "Tétine orthodontique",
    "USB Loader",
    "USBGecko",
    "Udu drums",
    "Ukraine",
    "Ukulélés",
    "Uncharted 2: Among Thieves",
    "Uncharted 3: Drake's Deception",
    "Uncharted 4: A Thief's End",
    "Uncharted: Drake's Fortune",
    "Unlaunch",
    "Unlocking Tool",
    "Uruguay",
    "Ustensiles",
    "Ustensiles de cuisine en acier inoxydable",
    "Ustensiles de cuisine en fonte",
    "Ustensiles de cuisine en silicone",
    "VMU (Visual Memory Unit)",
    "VR Controller",
    "Valise",
    "Valise cabine",
    "Valise de voyage",
    "Valise rigide",
    "Valise à roulettes",
    "Valve Index",
    "Vanuatu",
    "Vaporisateurs pour cheveux",
    "Veilleuse apaisante",
    "Veilleuse projecteur",
    "Venezuela",
    "Ventilateur de bureau",
    "Ventilateurs de refroidissement",
    "Ventilateurs pour ordinateurs",
    "Vernis à ongles",
    "Vernis à ongles à séchage rapide",
    "Vibration Feedback",
    "Violon",
    "Violon électrique",
    "Violoncelles",
    "Violons",
    "Vièles à roue",
    "Viêt Nam",
    "Voiture",
    "Voiture autonome",
    "Voiture de sport",
    "Voiture électrique",
    "Volant de course",
    "Volière pour oiseaux",
    "Vélo",
    "Vélo d'appartement",
    "Vélo de montagne",
    "Vélo de route",
    "Vélo pliant",
    "Vélo tout-terrain",
    "Vélo électrique",
    "Vélo électrique pliant",
    "Vélos d'appartement",
    "Vélos de montagne",
    "Vélos de route",
    "Vélos de spinning",
    "Vélos pliants",
    "Vélos électriques",
    "Vêtements",
    "Vêtements de cyclisme",
    "Vêtements de sport",
    "Vêtements de sport d'hiver",
    "Vêtements de yoga",
    "Vêtements et souvenirs du carnaval de Guadeloupe",
    "Vêtements pour chiens",
    "Wankels",
    "Webcams haute résolution",
    "Wii",
    "Wii Fit Balance Board",
    "Wii Remote",
    "Wii Softmod",
    "Wii U",
    "WiiU Homebrew",
    "Wireless Adapter",
    "World of Warcraft",
    "XKey",
    "Xbox",
    "Xbox 360",
    "Xbox 360 JTAG",
    "Xbox Kinect",
    "Xbox One",
    "Xbox Series X",
    "Xbox Series X Mod",
    "Xylophones",
    "Yorkshire Terrier",
    "Yémen",
    "ZX Spectrum",
    "Zambie",
    "Zapper",
    "Zapper Gun",
    "Zimbabwe",
    "Plug an*l",
    "Écharpe",
    "Échasses",
    "Échelle pour oiseaux",
    "Échelle télescopique",
    "Échiquier",
    "Éclairage LED intelligent",
    "Éclairages LED pour intérieur de voiture",
    "Écouteurs Bluetooth avec charge sans fil",
    "Écouteurs Bluetooth avec suivi d'activité",
    "Écouteurs Bluetooth résistants à la transpiration",
    "Écouteurs antibruit",
    "Écouteurs bouton",
    "Écouteurs bouton avec isolation phonique",
    "Écouteurs bouton sans fil",
    "Écouteurs de sport avec résistance à la sueur",
    "Écouteurs intra-auriculaires",
    "Écouteurs intra-auriculaires avec isolation phonique",
    "Écouteurs intra-auriculaires pour basses puissantes",
    "Écouteurs intra-auriculaires sans fil",
    "Écouteurs pliables",
    "Écouteurs sans fil",
    "Écouteurs sans fil avec annulation de bruit",
    "Écouteurs sans fil avec moniteurs de fréquence cardiaque",
    "Écouteurs sans fil avec qualité audio aptX",
    "Écouteurs sans fil avec réduction de bruit adaptative",
    "Écouteurs sans fil avec étui de charge portable",
    "Écouteurs sans fil sport",
    "Écouteurs sport",
    "Écouteurs sport résistants à l'eau",
    "Écouteurs sport sans fil avec moniteurs de fréquence cardiaque",
    "Écouteurs tour d'oreille",
    "Écran d'ordinateur",
    "Écrans LCD",
    "Écrans OLED",
    "Écrans de fumée pour soudure",
    "Écrans de protection pour coffre",
    "Écrans de protection pour pare-brise",
    "Écrans de protection solaire pour vitres",
    "Écrans solaires et crèmes solaires",
    "Écrans tactiles",
    "Éditions spéciales de films en coffret",
    "Égypte",
    "Émirats arabes unis",
    "Épagneul Breton",
    "Épagneul Japonais",
    "Épagneul Springer",
    "Épagneul Tibétain",
    "Épilateur électrique",
    "Épilateurs",
    "Éplucheurs",
    "Éponges de maquillage",
    "Éponges exfoliantes pour le corps",
    "Éponges pour tableau",
    "Éponges pour tableau avec motifs",
    "Éponges à récurer",
    "Épurateur d'air",
    "Épée en mousse",
    "Épée gonflable",
    "Équateur",
    "Équerre de précision",
    "Équerres",
    "Équerres réglables",
    "Équipement de camping léger",
    "Équipements de camping",
    "Équipements de crossfit",
    "Équipements de gym à domicile",
    "Équipements de musculation",
    "Érythrée",
    "Établi de travail",
    "Étagère murale",
    "Étain de soudure",
    "États-Unis",
    "Étau d'établi",
    "Étau de perceuse",
    "Étau parallèle",
    "Étendoir à linge",
    "Éthiopie",
    "Étiquettes pour marquer",
    "Étiquettes pour marquer avec designs",
    "Étui de protection pour téléphone",
    "Étui pour cartes de crédit",
    "Étui pour tablette",
    "Îles Cook",
    "Îles Marshall",
    "Îles Salomon"
  ]
  searchInput.addEventListener("input", function () {
    const inputText = searchInput.value;
    const words = inputText.split(" ");
    const lastWord = words[words.length - 1].toLowerCase();

    suggestionBox.innerHTML = "";

    if (lastWord !== "") {
      const normalizedLastWord = removeAccents(lastWord);

      const matchingSuggestions = suggestions
        .filter(suggestion =>
          removeAccents(suggestion.toLowerCase()).startsWith(normalizedLastWord)
        )
        

      matchingSuggestions.forEach(suggestion => {
        const suggestionElement = document.createElement("div");
        suggestionElement.classList.add("suggestion");
        suggestionElement.textContent = suggestion;
        suggestionElement.addEventListener("click", function () {
          words[words.length - 1] = suggestion;
          searchInput.value = words.join(" ");
          suggestionBox.style.display = "none";
        });
        suggestionBox.appendChild(suggestionElement);
      });

      if (matchingSuggestions.length > 0) {
        suggestionBox.style.display = "block";
      } else {
        suggestionBox.style.display = "none";
      }
    } else {
      suggestionBox.style.display = "none";
    }
  });

  document.addEventListener("click", function (event) {
    if (!event.target.closest(".searchbar-container")) {
      suggestionBox.style.display = "none";
    }
  });
});
